In [3]:
input = [1,2,3]
weight = [0.2,0.8,-0.5]
bias = 2


output = input[0]*weight[0]+input[1]*weight[1]+input[2]*weight[2]+bias
print(output)

2.3


In [4]:
input = [1,2,3,2.5]
weight = [0.2,0.8,-0.5,1.0]
bias = 2.0


output = input[0]*weight[0]+input[1]*weight[1]+input[2]*weight[2]+input[3]*weight[3]+bias
print(output)

4.8


In [5]:
input = [1,2,3,2.5]
weight1 = [0.2,0.8,-0.5,1.0]
weight2 = [0.5,-0.91,0.26,-0.5]
weight3 = [-0.26,-0.27,0.17,0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5


output = [input[0]*weight1[0]+input[1]*weight1[1]+input[2]*weight1[2]+input[3]*weight1[3]+bias1,
          input[0]*weight2[0]+input[1]*weight2[1]+input[2]*weight2[2]+input[3]*weight2[3]+bias2,
          input[0]*weight3[0]+input[1]*weight3[1]+input[2]*weight3[2]+input[3]*weight3[3]+bias3]
          
print(output)

[4.8, 1.21, 2.385]


In [6]:
input = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]
output = []
'''for n_weights,n_bias in zip(weights,biases):
  n_output = 0
  for n_input, weight in zip(input,n_weights):
    n_output += n_input*weight
  n_output += n_bias
  output.append(n_output)
print(output)'''

'for n_weights,n_bias in zip(weights,biases):\n  n_output = 0\n  for n_input, weight in zip(input,n_weights):\n    n_output += n_input*weight\n  n_output += n_bias\n  output.append(n_output)\nprint(output)'

In [7]:
for n_weights,n_biases in zip(weights,biases):
  n_output = 0
  for n_input, weight in zip(input, n_weights):
    n_output += n_input*weight
  n_output += n_biases
  output.append(n_output)
print(output)

[4.8, 1.21, 2.385]


In [8]:
#Using NUMPY Library
import numpy as np

In [12]:
input = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]
output = np.dot(weights, input) + biases
print(output)

[4.8   1.21  2.385]


In [15]:
#Batching - parallel operations with error
input = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]     

output = np.dot(weights, input) + biases
print(output)

NameError: ignored

In [17]:
#Batching - parallel operations
input = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]     

output = np.dot(input, np.array(weights).T) + biases # convert weights as np array and took a transpose of it
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [20]:
#Batching - parallel operations
input = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases =  [2, 3 ,0.5] 

weights1 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases1 = [-1, 2, -0.5]

L1_output = np.dot(input, np.array(weights).T) + biases
L2_output = np.dot(L1_output, np.array(weights1).T) + biases1
print(L2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [35]:
#Making an object
np.random.seed(0)
X = [[1.0, 2.0, 3.0, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print("-------------------------------------------------\n",layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
-------------------------------------------------
 [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
